//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LBTCPrototype.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AuthorizeResponse_AccessToken {
            get {
                return ((string)(this["AuthorizeResponse_AccessToken"]));
            }
            set {
                this["AuthorizeResponse_AccessToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AuthorizeResponse_AccessTokenScope {
            get {
                return ((string)(this["AuthorizeResponse_AccessTokenScope"]));
            }
            set {
                this["AuthorizeResponse_AccessTokenScope"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime AuthorizeResponse_AccessTokenExpiryTime {
            get {
                return ((global::System.DateTime)(this["AuthorizeResponse_AccessTokenExpiryTime"]));
            }
            set {
                this["AuthorizeResponse_AccessTokenExpiryTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AuthorizeResponse_AccessTokenRefreshToken {
            get {
                return ((string)(this["AuthorizeResponse_AccessTokenRefreshToken"]));
            }
            set {
                this["AuthorizeResponse_AccessTokenRefreshToken"] = value;
            }
        }
    }
}
